export type QuestionType = "textarea" | "text" | "email" | "tel" | "number" | "checkbox" | "radio" | "scale";

export type DiagnosticQuestion = {
  id: string;
  label: string;
  type?: QuestionType;
  helper?: string;
  options?: string[];
  required?: boolean;
};

export type DiagnosticSection = {
  id: string;
  title: string;
  rationale: string;
  questions: DiagnosticQuestion[];
};

const text = (id: string, label: string, helper?: string): DiagnosticQuestion => ({ id, label, helper, type: "textarea" });
const number = (id: string, label: string, helper?: string): DiagnosticQuestion => ({ id, label, helper, type: "number" });

export const DIAGNOSTIC_SECTIONS: DiagnosticSection[] = [
  {
    id: "contexto-oferta",
    title: "Contexto, estrutura e oferta educacional",
    rationale:
      "Antes de propor ações de marketing, precisamos entender o negócio como ele funciona: segmentos, capacidade, vagas, localização, ticket, serviços e prioridades reais de matrícula.",
    questions: [
      text("pitch_30s", "Em poucas frases, como você apresentaria a High Line School para uma família que nunca ouviu falar da escola? Escreva o pitch de 30 segundos."),
      {
        id: "segmentos_atendidos",
        label: "Quais segmentos e serviços a escola atende atualmente?",
        type: "checkbox",
        options: ["Berçário", "Educação Infantil", "Ensino Fundamental — Anos Iniciais", "Ensino Fundamental — Anos Finais", "Turno integral", "Contraturno", "Atividades complementares", "Outro"],
      },
      text("unidades_enderecos", "Em quais endereços ou unidades a escola opera hoje? Informe bairro, principais vias de acesso e eventuais planos de expansão física."),
      text("capacidade_maxima", "Qual é a capacidade máxima de alunos por unidade, segmento, série, turma e turno?"),
      text("alunos_atuais", "Quantos alunos a escola possui hoje? Separe por segmento, série, turma e turno, se possível."),
      text("vagas_prioritarias", "Quantas vagas estão abertas ou precisam ser preenchidas para o próximo ciclo de matrícula? Quais séries, turmas e turnos são prioritários?"),
      text("turmas_maior_procura", "Em quais turmas há maior procura, maior taxa de ocupação ou lista de espera?"),
      text("turmas_ociosidade", "Em quais turmas, séries ou turnos existe maior ociosidade hoje?"),
      text("mensalidades_taxas", "Qual é a mensalidade por segmento ou série? Inclua taxas de matrícula, material, alimentação, contraturno, transporte, uniforme ou serviços adicionais relevantes."),
      text("investimento_anual", "Qual é o investimento anual médio de uma família para estudar na High Line?"),
      text("condicoes_comerciais", "Quais formas de pagamento, descontos, bolsas, campanhas de matrícula ou condições comerciais existem hoje?"),
      text("limites_comerciais", "Quais condições comerciais a escola não aceita praticar por risco de comprometer margem, posicionamento ou percepção de valor?"),
      text("fontes_receita", "Quais são as três maiores fontes de receita da escola hoje?"),
      text("ofertas_estrategicas", "Há produtos, programas, serviços ou experiências educacionais que vocês gostariam de ampliar por serem estratégicos, rentáveis ou diferenciais?"),
      text("matricula_ideal", "Em uma frase, como seria a matrícula ideal para a High Line?"),
    ],
  },
  {
    id: "origem-essencia",
    title: "Origem, visão da fundadora e essência da marca",
    rationale:
      "Famílias escolhem uma visão de educação, um ambiente de confiança e um futuro possível para seus filhos. Este bloco revela a origem, as convicções e os valores que devem orientar a experiência da marca.",
    questions: [
      text("historia_high_line", "Como nasceu a ideia da High Line School? Conte a história desde o início."),
      text("momento_decisao_escola", "Em que momento você decidiu criar, comprar, liderar ou transformar uma escola?"),
      text("problema_educacao", "Qual problema da educação, da experiência escolar ou da relação entre escola e família você queria resolver?"),
      text("experiencia_influenciadora", "Houve alguma experiência pessoal, familiar ou profissional que influenciou essa decisão?"),
      text("visao_original", "Qual era a visão original da High Line quando a escola foi criada?"),
      text("encontrar_na_high_line", "O que vocês queriam que crianças e famílias encontrassem aqui que não encontravam em outras instituições?"),
      text("mudou_permaneceu", "O que mudou desde a fundação e o que permaneceu absolutamente inegociável?"),
      text("maior_desafio", "Qual foi o maior desafio já vivido pela escola? O que ele ensinou à gestão?"),
      text("maior_orgulho", "Qual foi o momento de maior orgulho da história da High Line até hoje?"),
      text("alem_conteudos", "O que você acredita que uma escola precisa fazer além de ensinar conteúdos?"),
      text("infancia_desejada", "Que tipo de infância você acredita que as crianças merecem viver?"),
      text("educacao_tradicional", "O que a educação tradicional, na sua visão, ainda deixa de desenvolver ou desenvolve de forma inadequada?"),
      text("competencias_futuro", "Quais competências acadêmicas, humanas, sociais e emocionais serão indispensáveis para os alunos no futuro?"),
      text("equilibrio_pedagogico", "Como a High Line equilibra acolhimento, autonomia, repertório, disciplina, excelência acadêmica e desenvolvimento socioemocional?"),
      text("criterios_inegociaveis", "Quando vocês tomam uma decisão pedagógica, quais critérios são inegociáveis?"),
      text("jamais_faria", "O que a escola jamais faria, mesmo que fosse tendência, aumentasse matrículas ou gerasse mais receita?"),
      text("levar_para_vida", "O que vocês desejam que um aluno leve da High Line para a vida, além do aprendizado formal?"),
      text("verdade_nao_comunicada", "Qual é a maior verdade sobre a High Line que o marketing atual ainda não consegue comunicar?"),
      text("entrega_melhor_que_explicacao", "O que a escola entrega melhor do que consegue explicar para uma família que ainda não a conhece?"),
      text("experiencia_emociona", "Qual parte da experiência High Line mais emociona ou orgulha você pessoalmente?"),
      text("frases_recomendacao", "Que frases você gostaria que pais e mães dissessem espontaneamente ao recomendar a escola?"),
      text("resposta_ideal_escolha", "Se uma família tivesse de explicar por que escolheu a High Line, qual deveria ser a resposta ideal?"),
      text("percepcao_equivocada", "Qual é a percepção equivocada mais comum sobre a escola?"),
      text("mensagem_receio", "Existe alguma mensagem importante que vocês têm receio de comunicar, mas acreditam profundamente?"),
      {
        id: "estilo_comunicacao",
        label: "Que estilo de comunicação representa a High Line? Marque todos que se aplicam.",
        type: "checkbox",
        options: ["Acolhedor", "Sofisticado", "Técnico", "Familiar", "Inspirador", "Provocador", "Contemporâneo", "Acadêmico", "Outro"],
      },
      text("estilo_comunicacao_explicacao", "Explique por que esses estilos representam a High Line e que tipo de linguagem, conteúdo ou estética não representa a escola de jeito nenhum."),
      text("visao_3_5_10", "Como você imagina a High Line daqui a 3, 5 e 10 anos?"),
      text("prioridade_crescimento", "A prioridade é crescer em número de alunos, abrir unidades, ampliar segmentos, consolidar excelência ou outra ambição? Explique."),
      text("posicao_goiania", "Que posição a High Line deve ocupar no cenário educacional de Goiânia?"),
      text("reconhecimento_missao", "Que reconhecimento faria você sentir que a missão da escola está sendo cumprida?"),
      text("legado", "Qual legado você gostaria de deixar por meio da High Line para alunos, famílias, equipe e cidade?"),
      text("referencia_nacional", "Se a High Line se tornasse referência nacional, por qual ideia ou experiência você gostaria que fosse conhecida?"),
      text("risco_crescimento", "Qual é o maior risco de crescer e perder a essência da escola?"),
      text("proteger_essencia", "O que precisa ser protegido para que o crescimento não transforme a High Line em mais uma escola?"),
    ],
  },
  {
    id: "publico-demanda",
    title: "Público atual, família ideal e demanda",
    rationale:
      "O desafio não é gerar mais leads a qualquer custo. É atrair e converter famílias compatíveis com a faixa de investimento, os valores e a proposta educacional da escola.",
    questions: [
      text("familias_atuais", "Quem são as famílias que estudam hoje na High Line? Descreva idade dos pais, profissões, faixa de renda, estilo de vida, interesses e expectativas predominantes."),
      text("geografia_familias", "Em quais bairros, condomínios, cidades ou regiões essas famílias moram?"),
      text("familia_permanece", "Qual é o perfil da família que mais valoriza e permanece na escola?"),
      text("razoes_escolha", "Quais são as razões mais comuns relatadas pelas famílias para escolher a High Line?"),
      {
        id: "origem_busca",
        label: "Quem normalmente inicia a busca pela escola?",
        type: "checkbox",
        options: ["Mãe", "Pai", "Ambos", "Avós", "Indicação de amigos", "Profissionais de saúde", "Outro"],
      },
      text("decisao_matricula", "Quem toma a decisão final de matrícula? Há outras pessoas que influenciam essa decisão?"),
      text("insegurancas_familia", "Quais são as maiores inseguranças de uma família antes de escolher ou trocar de escola?"),
      text("objecoes_jornada", "Quais são as principais objeções recebidas antes da visita, durante a visita e após a apresentação de investimento?"),
      text("leads_sem_perfil", "Quem são os leads que chegam hoje, mas claramente não têm perfil financeiro ou de expectativa compatível com a High Line?"),
      text("origem_leads_desalinhados", "Por que vocês acreditam que esses leads chegam: comunicação, anúncios, segmentação, oferta, região, formulário, preço não informado, parcerias ou outro motivo?"),
      text("pagamento_ou_valor", "O problema é capacidade de pagamento ou falta de percepção de valor antes da conversa sobre preço? Explique com exemplos."),
      text("familia_ideal", "Descreva a família ideal da High Line: perfil financeiro, bairro, profissão, valores, comportamento, repertório cultural, expectativa pedagógica e momento de vida."),
      text("circulos_oportunidade", "Quais regiões, condomínios, clubes, empresas, comunidades, profissionais e círculos sociais concentram a família que vocês desejam atrair?"),
      text("perfis_nao_desejados", "Quais perfis de família vocês não desejam atrair, mesmo que gerem grande volume de leads?"),
      text("familias_embaixadoras", "Quais famílias atuais seriam excelentes embaixadoras da escola? Por quê?"),
      text("familias_entrevista", "Se possível, indique três a cinco famílias que poderiam participar de uma entrevista de percepção de marca ou depoimento."),
    ],
  },
  {
    id: "produto-experiencia",
    title: "Produto pedagógico e experiência entregue",
    rationale:
      "A escola precisa transformar sua entrega pedagógica em evidências que uma família consegue ver, entender, valorizar e recomendar.",
    questions: [
      text("pilares_pedagogicos", "Quais são os pilares pedagógicos da High Line? Explique como cada um aparece na prática."),
      text("metodologia_rotina", "Como a metodologia funciona na rotina real das crianças, e não apenas no discurso institucional?"),
      text("padrao_high_line", "O que acontece em sala, nos projetos ou nos espaços da escola que mais representa o padrão High Line?"),
      text("adaptacao_acolhimento", "Como é o processo de adaptação e acolhimento de uma criança nova e de sua família?"),
      text("acompanhamento_desenvolvimento", "Como a escola acompanha o desenvolvimento acadêmico, socioemocional, comportamental e de autonomia dos alunos?"),
      text("devolutivas_pais", "Como os pais recebem devolutivas sobre o desenvolvimento dos filhos?"),
      text("diferencial_professores", "O que professores fazem de diferente em relação a outras escolas?"),
      text("desenvolvimento_docente", "Como a escola seleciona, forma, acompanha e desenvolve o corpo docente?"),
      text("proposta_componentes", "Como a proposta aparece em inglês, tecnologia, artes, leitura, esporte, cultura, natureza, projetos, avaliação e habilidades socioemocionais?"),
      text("protocolos_cuidado", "Quais são os protocolos e diferenciais de segurança, cuidado, saúde, alimentação e comunicação com as famílias?"),
      text("momentos_documentar", "Quais momentos da rotina merecem ser filmados ou documentados porque traduzem a essência da escola?"),
      text("projetos_marcantes", "Quais projetos, eventos, rituais ou experiências são mais marcantes para crianças e famílias?"),
      text("provas_qualidade", "Quais resultados concretos, portfólios, produções, indicadores ou trajetórias de alunos ajudam a provar a qualidade da escola?"),
      text("historias_transformacao", "Quais depoimentos ou histórias de famílias melhor demonstram a transformação entregue pela High Line?"),
      text("valor_subestimado", "Qual serviço, espaço, projeto ou prática é pouco valorizado hoje porque as famílias ainda não entendem toda a sua importância?"),
      text("percepcao_visita", "O que vocês gostariam que uma família percebesse durante uma visita, mas hoje muitas vezes passa despercebido?"),
    ],
  },
  {
    id: "concorrencia-posicionamento",
    title: "Concorrência, posicionamento e escolha",
    rationale:
      "A High Line disputa atenção com outras escolas, com a confiança na escola atual e com a comparação de valor versus investimento.",
    questions: [
      text("concorrentes_diretos", "Cite até cinco concorrentes diretos da High Line. Considere público, faixa de investimento, região, proposta e segmento atendido."),
      text("concorrentes_infantil", "Quais escolas concorrem mais diretamente na Educação Infantil?"),
      text("concorrentes_fundamental", "Quais escolas concorrem mais diretamente no Ensino Fundamental?"),
      text("concorrentes_forcas", "Para cada concorrente, o que ele faz bem em marca, comunicação, proposta pedagógica, atendimento, visita, comunidade ou experiência?"),
      text("high_line_melhor", "Para cada concorrente, em que a High Line é melhor hoje?"),
      text("concorrente_premium", "Qual concorrente é percebido como mais premium? Por quê?"),
      text("concorrente_indicacao", "Qual concorrente tem mais força de indicação e reputação entre famílias? Por quê?"),
      text("criterios_comparacao", "Quando uma família compara a High Line com outra escola, quais critérios entram mais frequentemente na decisão?"),
      text("motivos_concorrente", "Por que uma família poderia escolher um concorrente em vez da High Line hoje?"),
      text("lacuna_mercado", "Que lacuna de mercado os concorrentes não ocupam e que a High Line poderia dominar?"),
      text("marcas_admiradas", "Quais marcas, escolas ou empresas — de qualquer setor — vocês admiram pela experiência, atendimento e comunicação? O que especificamente admiram em cada uma?"),
      text("posicao_mente", "Em uma frase, qual deveria ser a posição da High Line na mente de uma família de alto padrão em Goiânia?"),
    ],
  },
  {
    id: "marketing-reputacao",
    title: "Marketing, presença digital e reputação",
    rationale:
      "Vamos identificar o que está sendo comunicado, para quem, por quais canais e com quais resultados, priorizando visitas qualificadas, matrículas e custo de aquisição.",
    questions: [
      text("acoes_marketing", "Quais ações de marketing foram realizadas nos últimos 12 meses?"),
      text("resultados_acoes", "Quais ações trouxeram mais leads? Quais trouxeram mais visitas? Quais trouxeram mais matrículas?"),
      text("leads_desqualificados", "Quais ações trouxeram maior volume de leads sem perfil financeiro ou sem compatibilidade com a escola?"),
      text("canais_links", "Em quais canais a High Line está presente hoje? Informe links de Instagram, Facebook, site, Google Business Profile, landing pages, WhatsApp, YouTube, TikTok, portais, plataformas e outros."),
      text("campanhas_ativas", "Quais campanhas de mídia paga estão rodando hoje? Informe objetivo, público, região, investimento, criativos e destino do lead."),
      text("investimento_midias", "Qual é o investimento mensal de mídia por canal?"),
      text("agencia_atual", "Existe uma agência atual? Quais são as responsabilidades dela: conteúdo, mídia, site, CRM, comercial, relatórios, produção audiovisual ou outras?"),
      text("agencia_faz_bem", "O que vocês sentem que a agência atual faz bem?"),
      text("agencia_nao_entende", "O que vocês sentem que a agência atual não entende, não entrega ou não consegue comunicar sobre a High Line?"),
      text("relatorios_agencia", "Quais relatórios a agência apresenta hoje? Com que frequência?"),
      text("indicadores_agencia", "Quais indicadores ela acompanha: alcance, leads, custo por lead, visitas, propostas, matrículas, CAC, origem das matrículas ou outro?"),
      { id: "origem_matricula_identificada", label: "A escola consegue identificar hoje a origem de cada matrícula?", type: "radio", options: ["Sim, de forma consistente", "Parcialmente", "Não"] },
      text("integracao_canais", "Há integração entre Meta Ads, Google Ads, site, formulários, WhatsApp, CRM e atendimento comercial?"),
      text("rastreio_configurado", "Existem pixel, Google Tag Manager, Google Analytics, eventos de conversão, UTMs e painel de indicadores configurados? Se souber, detalhe."),
      text("clareza_site", "O site explica com clareza os segmentos, a proposta pedagógica, os diferenciais, a localização e o caminho para agendar uma visita?"),
      text("paginas_segmentos", "Existem páginas específicas por segmento: Educação Infantil, Ensino Fundamental e demais ofertas?"),
      text("instagram_significado", "O Instagram atual mostra atividades ou explica o significado pedagógico e a transformação por trás delas?"),
      text("conteudos_qualificados", "Quais conteúdos geram mais alcance, salvamentos, mensagens, visitas ou conversas qualificadas?"),
      text("conteudos_sem_interesse", "Quais conteúdos parecem bonitos, mas não geram interesse real de matrícula?"),
      { id: "nota_presenca_digital", label: "Qual é a nota atual da presença digital da High Line?", type: "scale", helper: "Selecione uma nota de 0 a 10 e explique a razão na pergunta seguinte." },
      text("nota_presenca_digital_porque", "Por que você atribui essa nota à presença digital da High Line?"),
      text("acervo_disponivel", "A escola possui fotos, vídeos, histórias, professores e famílias disponíveis para produção recorrente de conteúdo? O que já existe de acervo?"),
      text("avaliacoes_google", "Quantas avaliações a escola possui no Google? Qual é a nota? Como as avaliações e críticas são respondidas?"),
      text("elogios_frequentes", "Quais elogios são mais frequentes nas avaliações, mensagens e conversas com pais?"),
      text("criticas_alerta", "Quais críticas ou reclamações acenderam alerta nos últimos 12 meses?"),
      text("comunicacao_proibida", "Que tipo de conteúdo, mensagem, campanha ou linguagem não deve ser associada à High Line de forma alguma?"),
    ],
  },
  {
    id: "comercial-conversao",
    title: "Comercial, visita e conversão de matrículas",
    rationale:
      "Matrícula é consequência de uma jornada. Este bloco mapeia o funil para descobrir onde os leads se perdem, do primeiro contato ao follow-up.",
    questions: [
      text("leads_por_mes", "Quantos leads a escola recebeu por mês nos últimos 6 a 12 meses?"),
      text("leads_por_canal", "Quantos leads vieram por canal: indicação, Instagram, Meta Ads, Google, site, WhatsApp, eventos, parceiros, portais e outros?"),
      number("leads_contatados", "Quantos leads foram contatados?"),
      number("leads_qualificados", "Quantos foram considerados qualificados?"),
      number("visitas_agendadas", "Quantas visitas foram agendadas?"),
      number("visitas_realizadas", "Quantas visitas foram efetivamente realizadas?"),
      number("propostas_enviadas", "Quantas famílias receberam proposta, condições ou orientação de matrícula?"),
      number("matriculas_fechadas", "Quantas matrículas foram fechadas?"),
      text("matriculas_perdidas", "Quantas matrículas foram perdidas? Quais foram os principais motivos registrados?"),
      text("dados_conversao", "Quais dados a escola já possui para calcular taxas de conversão por etapa e custo por matrícula?"),
      text("canais_entrada_leads", "Por quais canais os leads entram hoje?"),
      text("time_primeiro_atendimento", "Quem realiza o primeiro atendimento? Informe cargo, quantidade de pessoas e disponibilidade."),
      text("tempo_primeira_resposta", "Qual é o tempo médio de primeira resposta para leads de cada canal?"),
      { id: "atendimento_fora_horario", label: "Existe atendimento fora do horário comercial ou em fins de semana?", type: "radio", options: ["Sim", "Não", "Em alguns períodos"] },
      text("roteiro_atendimento", "Há um roteiro de primeiro atendimento, qualificação, agendamento, apresentação de preço e follow-up?"),
      text("perguntas_qualificacao", "Quais perguntas são feitas para entender série, idade da criança, bairro, momento de decisão e necessidade da família?"),
      text("momento_investimento", "Em que momento a mensalidade ou investimento é informado?"),
      text("construcao_valor", "Como o time constrói percepção de valor antes de falar de preço?"),
      text("tratamento_objecoes", "Como são tratadas objeções sobre preço, localização, metodologia, adaptação, segurança e comparação com concorrentes?"),
      text("crm_historico", "O comercial registra informações e histórico em CRM? Qual sistema utiliza?"),
      text("visita_passo_a_passo", "Como funciona a visita à escola, passo a passo?"),
      text("quem_recebe_visita", "Quem recebe a família e quem apresenta a proposta pedagógica?"),
      text("duracao_visita", "Quanto tempo dura a visita?"),
      text("experiencia_visita", "O que a família vê, ouve, sente e recebe durante a visita?"),
      text("visita_adaptada", "A visita é adaptada para o segmento e a necessidade da criança?"),
      text("provas_visita", "Quais provas de valor são apresentadas: rotina, sala, professores, projetos, portfólios, depoimentos, dados, ambiente, histórias e resultados?"),
      text("kit_matricula", "Há uma apresentação comercial ou kit de matrícula por segmento?"),
      text("mesmo_dia_visita", "O que acontece no mesmo dia da visita?"),
      text("cadencia_followup", "Como é a cadência de follow-up após a visita? Informe número de contatos, prazos, canais e responsáveis."),
      text("desistencia_pos_visita", "Quais são os principais motivos de desistência após a visita?"),
      text("ponto_perda", "Em qual ponto da jornada a escola acredita perder mais famílias hoje?"),
      text("visita_inesquecivel", "O que seria uma visita inesquecível e coerente com a experiência premium prometida pela High Line?"),
    ],
  },
  {
    id: "indicacao-confianca",
    title: "Indicação, comunidade e confiança",
    rationale:
      "Indicação e reputação são canais centrais de aquisição. Este bloco identifica como a confiança circula hoje e como transformá-la em um sistema ético, elegante e mensurável.",
    questions: [
      text("percentual_indicacao", "Qual percentual aproximado das matrículas vem por indicação?"),
      { id: "indicacao_registrada", label: "A origem indicação é registrada com o nome da pessoa ou família que indicou?", type: "radio", options: ["Sim", "Parcialmente", "Não"] },
      text("familias_indicam", "Quais famílias mais indicam a High Line hoje? Por que você acredita que elas indicam?"),
      text("programa_indicacao", "Existe algum programa, ação ou reconhecimento estruturado de indicação?"),
      text("agradecimento_indicacao", "Como a escola agradece, reconhece ou mantém relacionamento com famílias que indicam?"),
      text("momentos_recomendar", "Em quais momentos da jornada uma família fica mais propensa a recomendar a escola?"),
      text("experiencias_orgulho", "Quais experiências da High Line mais geram orgulho nos pais?"),
      text("historias_depoimentos", "Quais histórias de alunos, famílias e professores podem se tornar depoimentos fortes para comunicação e comercial?"),
      text("eventos_comunidade", "A escola já realiza eventos de portas abertas, cafés com famílias, encontros pedagógicos, aulas experimentais, palestras ou ações de comunidade? O que funciona melhor?"),
      text("parcerias_publico", "Quais parcerias poderiam aproximar a escola do público desejado: condomínios, clubes, pediatras, psicólogos, empresas, arquitetos, espaços infantis, maternidades, consultores familiares e outros?"),
      text("monitoramento_reputacao", "Como a escola monitora reputação em Google, redes sociais, grupos de pais e conversas com famílias?"),
      text("resposta_critica", "Quando surge uma crítica, insatisfação ou conflito, como a escola responde e acompanha a solução?"),
      text("indicacao_espontanea", "O que precisaria acontecer para uma família dizer: Eu não só recomendo a High Line; eu faço questão de indicar?"),
    ],
  },
  {
    id: "operacao-crescimento",
    title: "Operação, equipe e capacidade de crescimento",
    rationale:
      "Não adianta ampliar a captação se a escola não consegue entregar uma experiência coerente, acolher novas famílias e manter qualidade.",
    questions: [
      text("crescimento_seguro", "Até quanto a escola consegue crescer em número de matrículas e receita sem ampliar estrutura física, contratar novas pessoas ou comprometer a experiência?"),
      text("turmas_crescimento", "Quais segmentos ou turmas suportam mais crescimento imediato?"),
      text("gargalos_operacionais", "Existem gargalos de espaço, equipe, professores, atendimento, alimentação, transporte, segurança, processos ou comunicação com pais?"),
      text("periodos_pressao", "Em quais momentos do ano a operação fica mais pressionada?"),
      text("areas_impacto_crescimento", "Quais serviços ou áreas podem ser impactados negativamente se houver crescimento rápido?"),
      text("planejamento_expansao", "Como a escola planeja novas contratações, abertura de turmas e investimentos em estrutura?"),
      text("indicadores_operacionais", "Quais indicadores operacionais são acompanhados para garantir qualidade?"),
      text("retencao_satisfacao", "Quais desafios de retenção, rematrícula ou satisfação de famílias existem hoje?"),
      text("reclamacoes_antes_escala", "Há demandas ou reclamações recorrentes que precisam ser resolvidas antes de escalar a captação?"),
      text("oportunidade_operacional", "Qual é a maior oportunidade operacional que, se organizada, aumentaria a percepção de valor da família?"),
    ],
  },
  {
    id: "metas-governanca",
    title: "Metas, governança e prioridades",
    rationale:
      "A estratégia precisa ter metas claras, responsáveis definidos, orçamento, velocidade de aprovação e disponibilidade de execução.",
    questions: [
      text("matriculas_3_6_12", "Quantas matrículas líquidas a High Line precisa conquistar nos próximos 3, 6 e 12 meses?"),
      text("meta_ocupacao", "Qual é a meta de ocupação por segmento, série e turno?"),
      text("turmas_prioridade", "Quais séries ou turmas devem ser priorizadas primeiro?"),
      text("sucesso_12_meses", "O que representa sucesso para a escola nos próximos 12 meses: faturamento, matrículas, ocupação, reconhecimento, retenção, expansão ou outro?"),
      text("faturamento_incremental", "Qual é o faturamento incremental desejado ou necessário?"),
      text("investimento_sustentavel", "Qual investimento mensal em mídia a escola considera sustentável durante pelo menos 90 dias?"),
      text("orcamento_estrutura", "Existe orçamento para produção audiovisual, eventos, site, CRM, automação, materiais de visita e treinamento comercial?"),
      text("ponto_contato", "Quem será o principal ponto de contato com a VirtruvIA no dia a dia? Informe nome, cargo, telefone e disponibilidade."),
      text("aprovacoes", "Quem aprova conteúdo e postagens, campanhas e promoções, investimento de mídia, mudanças no comercial, materiais institucionais e pedagógicos?"),
      text("prazo_aprovacao", "Qual é o prazo máximo aceitável para aprovação de materiais e decisões?"),
      text("responsavel_comercial", "Quem será responsável pela operação comercial diária e pela atualização do CRM?"),
      text("aceite_processos", "A equipe aceita implementar novos roteiros, SLA de atendimento, rotina de follow-up, gestão de pipeline e acompanhamento de indicadores? Quais limitações existem?"),
      text("acessos_auditoria", "Quais acessos, relatórios e dados a escola consegue disponibilizar para a auditoria?"),
      text("iniciativas_restritas", "Existe alguma iniciativa que não pode ser feita por questões pedagógicas, jurídicas, reputacionais ou de posicionamento?"),
      text("preocupacao_gestao", "Qual é a maior preocupação da gestão ao iniciar esse projeto?"),
      text("parceria_90_dias", "O que precisaria acontecer para você afirmar, ao final de 90 dias, que a parceria está no caminho certo?"),
    ],
  },
];

export const MATERIALS_REQUESTED = [
  "Organograma e lista dos principais responsáveis por pedagógico, comercial, atendimento e marketing.",
  "Número de alunos, vagas, ocupação e lista de espera por turma, série e turno.",
  "Tabela de mensalidades, taxas, produtos, serviços e política comercial.",
  "Relatórios de leads, visitas, propostas, matrículas e motivos de perda dos últimos 6 a 12 meses.",
  "Origem de cada matrícula, relatórios da agência atual e investimento de mídia por canal e mês.",
  "Acessos ou exportações de Meta Ads, Google Ads, Google Analytics, Tag Manager, CRM e WhatsApp Business, se aplicável.",
  "Links de canais, criativos, copies, vídeos, fotos e campanhas utilizadas nos últimos 12 meses.",
  "Apresentações pedagógicas, materiais de matrícula, kit de visita, contrato e comunicações de rematrícula.",
  "Avaliações do Google, elogios, críticas, pesquisas de satisfação e lista de concorrentes prioritários.",
  "Materiais que documentem metodologia, projetos, eventos, resultados e diferenciais pedagógicos.",
];

export const TOTAL_QUESTIONS = DIAGNOSTIC_SECTIONS.reduce((total, section) => total + section.questions.length, 0);
