-- Diagnóstico 360º High Line School: dados privados de submissões, materiais e comprovantes.
create table if not exists public.diagnostic_submissions (
  id bigint generated by default as identity primary key,
  respondent_name text not null check (char_length(respondent_name) between 2 and 191),
  respondent_role text,
  respondent_email text not null check (char_length(respondent_email) <= 320),
  respondent_phone text,
  answers jsonb not null default '{}'::jsonb,
  email_status text not null default 'pending' check (email_status in ('pending', 'sent', 'failed')),
  email_error text,
  receipt_storage_key text,
  receipt_access_token text unique,
  receipt_expires_at timestamptz,
  submitted_at timestamptz not null default now()
);

create index if not exists diagnostic_submissions_submitted_at_idx
  on public.diagnostic_submissions (submitted_at desc);
create index if not exists diagnostic_submissions_receipt_expiry_idx
  on public.diagnostic_submissions (receipt_expires_at);

create table if not exists public.diagnostic_materials (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.diagnostic_submissions(id) on delete cascade,
  category text not null check (category in ('digital', 'commercial', 'institutional')),
  notes text,
  file_name text,
  storage_key text,
  file_url text,
  content_type text,
  size_bytes integer check (size_bytes is null or size_bytes > 0),
  created_at timestamptz not null default now()
);

create index if not exists diagnostic_materials_submission_id_idx
  on public.diagnostic_materials (submission_id);

alter table public.diagnostic_submissions enable row level security;
alter table public.diagnostic_materials enable row level security;

-- O bucket é privado; apenas a API de servidor usando a chave de serviço acessa arquivos.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'diagnostic-assets',
  'diagnostic-assets',
  false,
  3145728,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'image/jpeg',
    'image/png',
    'image/webp',
    'text/plain',
    'text/csv'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
